language: android
android:
  components:
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-25.0.1
    - android-25
    - extra-android-m2repository
    - extra-google-m2repository

  jdk:
  - oraclejdk8

  before_install:
  - "chmod +x gradlew"
  - "chmod +x build.sh"

script:
   - ./gradlew build connectedCheck
